name: Build/push edge-2.9.9 image

on:
  workflow_dispatch:
  push:
    branches: [sddi-odp-2.9.9]
    paths:
      - sddi-odp/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ['sddi-odp']
      fail-fast: true
      max-parallel: 1
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/johnny-space/ckan-${{ matrix.context }}
          tags: |
            type=edge,branch=sddi-odp-2.9.9,suffix=-2.9.9
            type=raw,value=odp-katalog-1.1.0
          labels: |
            maintainer=Ondics GmbH, Esslingen am Neckar
            org.opencontainers.image.vendor=Ondics GmbH, Esslingen am Neckar
            org.opencontainers.image.title=ckan-sddi-docker

      - name: Build and publish ${{ env.REGISTRY }}/johnny-space/ckan-${{ matrix.context }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASEIMAGE_VERSION=edge

      - name: Extract metadata (tags, labels) for debug docker image
        id: meta-debug
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/johnny-space/ckan-${{ matrix.context }}
          tags: |
            type=edge,branch=sddi-odp-2.9.9,suffix=-2.9.9-debug
            type=raw,value=odp-katalog-1.1.0-debug
          labels: |
            maintainer=Ondics GmbH, Esslingen am Neckar
            org.opencontainers.image.vendor=Ondics GmbH, Esslingen am Neckar
            org.opencontainers.image.title=ckan-sddi-docker

      - name: Build and publish ${{ env.REGISTRY }}/johnny-space/ckan-${{ matrix.context }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile.debug
          push: true
          tags: ${{ steps.meta-debug.outputs.tags }}
          labels: ${{ steps.meta-debug.outputs.labels }}
          build-args: |
            BASEIMAGE_VERSION=edge-2.9.9
